version: "3.9"

services:
  elib-database:
    restart: always
    image: postgres:latest
    container_name: elib-database
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data

  elib-server:
    restart: always
    build: ./backend
    container_name: elib-server
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    expose:
      - 8000
    depends_on:
      - elib-database
    
  elib-frontend:
    restart: always
    build: ./frontend
    container_name: elib-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - elib-database
      - elib-server

  elib-nginx:
    restart: always
    image: nginx:latest
    container_name: elib-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./backend:/app/backend:ro
    environment:
      - NGINX_SSL_KEY_PASSWORD=capy
    depends_on:
      - elib-server

volumes:
  db-data:
