version: "3.9"

services:
  elib-database:
    restart: always
    image: postgres:latest
    container_name: elib-database
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data

  elib-pgbouncer:
    restart: always
    image: pgbouncer/pgbouncer
    container_name: elib-pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ./backend/.env
    depends_on:
      - elib-database

  elib-server:
    restart: always
    build: ./backend
    container_name: elib-server
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - elib-database
      - elib-pgbouncer
    
  elib-frontend:
    restart: always
    build: ./frontend
    container_name: elib-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - elib-database
      - elib-pgbouncer
      - elib-server

volumes:
  db-data: