# Generated by Django 4.2.1 on 2023-05-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="BookLanguages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elibrary.book"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elibrary.language",
                    ),
                ),
            ],
            options={
                "db_table": "book_languages",
            },
        ),
        migrations.CreateModel(
            name="BookGenre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elibrary.book"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elibrary.genre"
                    ),
                ),
            ],
            options={
                "db_table": "book_genre",
            },
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elibrary.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elibrary.book"
                    ),
                ),
            ],
            options={
                "db_table": "book_author",
            },
        ),
    ]
