from decouple import config

DB_NAME = config("PGBOUNCER_DATABASES")
DB_HOST = config("PGBOUNCER_DATABASES_HOST")
DB_PASS = config("PGBOUNCER_DATABASES_PASSWORD")
DB_PORT = config("PGBOUNCER_DATABASES_PORT")
DB_USER = config("PGBOUNCER_DATABASES_USER")

SECRET_AUTH = config("SECRET_AUTH")
