"""book and extans

Revision ID: aca149efd1c7
Revises: b8c405050881
Create Date: 2023-05-12 18:15:38.647561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aca149efd1c7"
down_revision = "b8c405050881"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "el_library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["el_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_el_library_user_id"), "el_library", ["user_id"], unique=True
    )
    op.create_table(
        "el_book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["el_library.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "el_user_book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["el_book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["el_library.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("el_user_book")
    op.drop_table("el_book")
    op.drop_index(op.f("ix_el_library_user_id"), table_name="el_library")
    op.drop_table("el_library")
    # ### end Alembic commands ###
