"""[update] name of password fields

Revision ID: e68f3a4c9544
Revises: ad0533d3639e
Create Date: 2023-05-12 10:53:52.913984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68f3a4c9544'
down_revision = 'ad0533d3639e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('el_user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('el_user', sa.Column('password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
