"""add user book into library model

Revision ID: f4d3edd02022
Revises: bc253e06008f
Create Date: 2023-05-14 20:06:01.806316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d3edd02022'
down_revision = 'bc253e06008f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('el_library_id_fkey', 'el_library', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('el_library_id_fkey', 'el_library', 'el_user_book', ['id'], ['id'])
    # ### end Alembic commands ###
