"""fix user book and library keys

Revision ID: bc253e06008f
Revises: aca149efd1c7
Create Date: 2023-05-14 20:03:18.892301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc253e06008f'
down_revision = 'aca149efd1c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('el_library', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_el_library_user_id', table_name='el_library')
    op.create_foreign_key(None, 'el_library', 'el_user_book', ['id'], ['id'])
    op.drop_constraint('el_user_book_library_id_fkey', 'el_user_book', type_='foreignkey')
    op.drop_column('el_user_book', 'library_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('el_user_book', sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('el_user_book_library_id_fkey', 'el_user_book', 'el_library', ['library_id'], ['id'])
    op.drop_constraint(None, 'el_library', type_='foreignkey')
    op.create_index('ix_el_library_user_id', 'el_library', ['user_id'], unique=False)
    op.alter_column('el_library', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
